# fly.toml app configuration file generated for jskid on 2026-04-27T00:23:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jskid'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '30s'
    timeout = '10s'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
